language: shell
os: linux

services:
  - docker

jobs:
  include:
    - stage: Build binaries

      # This must weirdly not have a dash, otherwise an empty job is created
      env: BUILD=linux
    - env: BUILD=windows
    - env: BUILD=armv6hf
    - env: BUILD=aarch64
    - env: BUILD=osx
      os: osx

    - stage: Deploy docker image
      if: branch = master
      script:
        - true

before_install: |
  DOCKER_BASE="lolbert/shellcheck"
  DOCKER_BUILDS=""
  TAGS=""
  test "$TRAVIS_BRANCH" = master && TAGS="$TAGS latest" || true
  test -n "$TRAVIS_TAG"          && TAGS="$TAGS stable $TRAVIS_TAG" || true
  echo "Tags are $TAGS"

script:
  - mkdir -p deploy
  - source ./.compile_binaries
  - ./striptests
  - set -ex; build_"$BUILD"; set +x;
  - ./.prepare_deploy

after_failure: |
  id
  pwd
  df -h
  find . -name '*.log' -type f -exec grep "" /dev/null {} +
  find . -ls


deploy:
  - provider: gcs
    access_key_id: GOOG7MDN7WEH6IIGBDCA
    secret_access_key:
      secure: Bcx2cT0/E2ikj7sdamVq52xlLZF9dz9ojGPtoKfPyQhkkZa+McVI4xgUSuyyoSxyKj77sofx2y8m6PJYYumT4g5hREV1tfeUkl0J2DQFMbGDYEt7kxVkXCxojNvhHwTzLFv0ezstrxWWxQm81BfQQ4U9lggRXtndAP4czZnOeHPINPSiue1QNwRAEw05r5UoIUJXy/5xyUrjIxn381pAs+gJqP2COeN9kTKYH53nS/AAws29RprfZFnPlo7xxWmcjRcdS5KPdGXI/c6tQp5zl2iTh510VC1PN2w1Wvnn/oNWhiNdqPyVDsojIX5+sS3nejzJA+KFMxXSBlyXIY3wPpS/MdscU79X6Q5f9ivsFfsm7gNBmxHUPNn0HAvU4ROT/CCE9j6jSbs5PC7QBo3CK4++jxAwE/pd9HUc2rs3k0ofx3rgveJ7txpy5yPKfwIIBi98kVKlC4w7dLvNTOfjW1Imt2yH87XTfsE0UIG9st1WII6s4l/WgBx2GuwKdt6+3QUYiAlCFckkxWi+fAvpHZUEL43Qxub5fN+ZV7Zib1n7opchH4QKGBb6/y0WaDCmtCfu0lppoe/TH6saOTjDFj67NJSElK6ZDxGZ3uw4R+ret2gm6WRKT2Oeub8J33VzSa7VkmFpMPrAAfPa9N1Z4ewBLoTmvxSg2A0dDrCdJio=
    bucket: shellcheck
    local_dir: deploy
    on:
      repo: koalaman/travistest
      condition: 0 = 1
      all_branches: true

  - provider: releases
    api_key:
      secure: gXq8QVM5n1wedlcygLM/vtwvspMvg6otmq/Yg5Y+I9VgmsSDNBzHp/MCKCR5z6fPB8+PGli3jJg+XRuUznqYdZefY21KizFAzD+SVqmvGysKqAZqC0CCjWWoq3jLXoMJZ1WcfR4yubQD8o5ziQxbXB21fPC7v2kb9h5ihWhKqG8Jha3otX3KZ3+PUMZhdetE4TnSq4AMAX7ceKxWB/1il8W97Ju6R2WwuwZd9PRsDRHsSjZyLdQxtIPezhEIkul1C5QK/9OTjlPHopjY/aDXRhz2MGgv6MK/k8D69p80Hb4hEMnlSctyCXx4r8u9q5eFAmInoh7ua4RylwEV/kV6iKUYxCnb2yqwThzW4A1uMAYNmXh5LW3hWrg+8hKn8NAeRu9FNWS1ACSDmQeJFOqTYQSfkP6COcMGW9msLeZIZWRvBOkA16ZVHBk4UL/9KBJ4ErhGRG7WwZKGrBUUgftr+L4GDk5itGMmMMYJdQtl5BtMV+jcMV7gHVawLQu1dovrWNE52Cabwgl+w/AU7GuZ7koPBHhjrcpqSviMawRHHDFYBRlmbPsmyTzh8x+Z58J/hV9/2gaL3IT/p7I8QW89ZCmLommplxKFnk3cntCqwR0TPD7Y28fHfdOW0sClCRaphmpDSE3HluqRIX2LsfNiCwWsQp2K5RTThd9bRhSQuTY=
    file_glob: true
    file: deploy/*
    on:
      repo: koalaman/travistest
      condition: $TRAVIS_BUILD_STAGE_NAME = "Build binaries"

